Error for file Data/Sri Lanka Weekly Reports Post 2013/en_6585409665879_Vol_50_no_49-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 260, in convert_to_table
    long, lat, region_type, country_code, region_boundary = get_location_info(location_name)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\../../Modules\location_interface.py", line 128, in get_location_info
    raise ValueError
ValueError

Error for file Data/Sri Lanka Weekly Reports Post 2013/en_658bf46e36e50_Vol_50_no_50-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 260, in convert_to_table
    long, lat, region_type, country_code, region_boundary = get_location_info(location_name)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\../../Modules\location_interface.py", line 128, in get_location_info
    raise ValueError
ValueError

Error for file Data/Sri Lanka Weekly Reports Post 2013/en_65938b8caa4b2_Vol_50_no_51-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 260, in convert_to_table
    long, lat, region_type, country_code, region_boundary = get_location_info(location_name)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\../../Modules\location_interface.py", line 128, in get_location_info
    raise ValueError
ValueError

Error for file Data/Sri Lanka Weekly Reports Post 2013/en_659e7c802c6b3_Vol_50_no_52-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 260, in convert_to_table
    long, lat, region_type, country_code, region_boundary = get_location_info(location_name)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\../../Modules\location_interface.py", line 128, in get_location_info
    raise ValueError
ValueError

Error for file Data/Sri Lanka Weekly Reports Post 2013/en_65b8d3689b762_Vol_51_no_01-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 260, in convert_to_table
    long, lat, region_type, country_code, region_boundary = get_location_info(location_name)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\../../Modules\location_interface.py", line 128, in get_location_info
    raise ValueError
ValueError

Error for file Data/Sri Lanka Weekly Reports Post 2013/en_65b8d4365985a_Vol_51_no_02-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 260, in convert_to_table
    long, lat, region_type, country_code, region_boundary = get_location_info(location_name)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\../../Modules\location_interface.py", line 128, in get_location_info
    raise ValueError
ValueError

Error for file Data/Sri Lanka Weekly Reports Post 2013/en_65c24c8b0418e_Vol_51_no_04-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 260, in convert_to_table
    long, lat, region_type, country_code, region_boundary = get_location_info(location_name)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\../../Modules\location_interface.py", line 128, in get_location_info
    raise ValueError
ValueError

Error for file Data/Sri Lanka Weekly Reports Post 2013/en_65c3284dbe388_Vol_51_no_03-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 260, in convert_to_table
    long, lat, region_type, country_code, region_boundary = get_location_info(location_name)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\../../Modules\location_interface.py", line 128, in get_location_info
    raise ValueError
ValueError

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_40_no_22_english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 260, in convert_to_table
    long, lat, region_type, country_code, region_boundary = get_location_info(location_name)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\../../Modules\location_interface.py", line 128, in get_location_info
    raise ValueError
ValueError

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_40_no_23_english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 260, in convert_to_table
    long, lat, region_type, country_code, region_boundary = get_location_info(location_name)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\../../Modules\location_interface.py", line 128, in get_location_info
    raise ValueError
ValueError

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_40_no_24_english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 263, in convert_to_table
    disease_name = labels[j//2]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_40_no_25_english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 263, in convert_to_table
    disease_name = labels[j//2]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_40_no_26_english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 263, in convert_to_table
    disease_name = labels[j//2]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_40_no_27_english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 263, in convert_to_table
    disease_name = labels[j//2]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_40_no_28_english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 260, in convert_to_table
    long, lat, region_type, country_code, region_boundary = get_location_info(location_name)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\../../Modules\location_interface.py", line 128, in get_location_info
    raise ValueError
ValueError

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_40_no_29_english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 263, in convert_to_table
    disease_name = labels[j//2]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_40_no_30_english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 263, in convert_to_table
    disease_name = labels[j//2]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_40_no_31_english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 263, in convert_to_table
    disease_name = labels[j//2]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_40_no_32_english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 263, in convert_to_table
    disease_name = labels[j//2]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_40_no_33_english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 263, in convert_to_table
    disease_name = labels[j//2]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_40_no_34_english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 263, in convert_to_table
    disease_name = labels[j//2]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_40_no_35_english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 263, in convert_to_table
    disease_name = labels[j//2]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_40_no_36_english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 263, in convert_to_table
    disease_name = labels[j//2]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_40_no_37_english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 263, in convert_to_table
    disease_name = labels[j//2]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_40_no_38_english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 263, in convert_to_table
    disease_name = labels[j//2]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_40_no_39_english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 263, in convert_to_table
    disease_name = labels[j//2]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_40_no_40_english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 263, in convert_to_table
    disease_name = labels[j//2]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_40_no_41_english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 263, in convert_to_table
    disease_name = labels[j//2]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_40_no_42_english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 263, in convert_to_table
    disease_name = labels[j//2]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_40_no_43_english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 263, in convert_to_table
    disease_name = labels[j//2]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_40_no_44_english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 263, in convert_to_table
    disease_name = labels[j//2]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_40_no_45_english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 260, in convert_to_table
    long, lat, region_type, country_code, region_boundary = get_location_info(location_name)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\../../Modules\location_interface.py", line 128, in get_location_info
    raise ValueError
ValueError

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_40_no_46_english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 260, in convert_to_table
    long, lat, region_type, country_code, region_boundary = get_location_info(location_name)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\../../Modules\location_interface.py", line 128, in get_location_info
    raise ValueError
ValueError

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_40_no_47_english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 260, in convert_to_table
    long, lat, region_type, country_code, region_boundary = get_location_info(location_name)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\../../Modules\location_interface.py", line 128, in get_location_info
    raise ValueError
ValueError

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_40_no_48_english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 260, in convert_to_table
    long, lat, region_type, country_code, region_boundary = get_location_info(location_name)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\../../Modules\location_interface.py", line 128, in get_location_info
    raise ValueError
ValueError

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_40_no_49_english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 33, in extract_to_table
    important_text,timestamps = extract_data_from_rtf(rtf_data)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\rtf_extractor.py", line 110, in extract_data_from_rtf
    end_date = parse(f"{year} {month} {day}")
  File "C:\Users\pasarm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\dateutil\parser\_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\pasarm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\dateutil\parser\_parser.py", line 643, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: 2013 Dece 06

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_40_no_50_english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 260, in convert_to_table
    long, lat, region_type, country_code, region_boundary = get_location_info(location_name)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\../../Modules\location_interface.py", line 128, in get_location_info
    raise ValueError
ValueError

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_40_no_51_english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 260, in convert_to_table
    long, lat, region_type, country_code, region_boundary = get_location_info(location_name)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\../../Modules\location_interface.py", line 128, in get_location_info
    raise ValueError
ValueError

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_40_no_52_english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 260, in convert_to_table
    long, lat, region_type, country_code, region_boundary = get_location_info(location_name)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\../../Modules\location_interface.py", line 128, in get_location_info
    raise ValueError
ValueError

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_41_no_01-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_41_no_02-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_41_no_03-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_41_no_05-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_41_no_06-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_41_no_07-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_41_no_09-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_41_no_10-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_41_no_11-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_41_no_13-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_41_no_14-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_41_no_15-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_41_no_16-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_41_no_18-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_41_no_21-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_41_no_23-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_41_no_24-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_41_no_25-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_41_no_26-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_41_no_27-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_41_no_30-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_41_no_31-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_41_no_33-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_41_no_34-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 260, in convert_to_table
    long, lat, region_type, country_code, region_boundary = get_location_info(location_name)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\../../Modules\location_interface.py", line 128, in get_location_info
    raise ValueError
ValueError

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_41_no_35-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_41_no_38-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_41_no_39-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_41_no_40-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_41_no_41-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_42_no_04-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_42_no_26-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_42_no_32-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 263, in convert_to_table
    disease_name = labels[j//2]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_42_no_45-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_42_no_50-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 263, in convert_to_table
    disease_name = labels[j//2]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_43_no_03-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 263, in convert_to_table
    disease_name = labels[j//2]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_43_no_04-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 263, in convert_to_table
    disease_name = labels[j//2]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_43_no_05-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_43_no_21-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 260, in convert_to_table
    long, lat, region_type, country_code, region_boundary = get_location_info(location_name)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\../../Modules\location_interface.py", line 128, in get_location_info
    raise ValueError
ValueError

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_43_no_34-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 263, in convert_to_table
    disease_name = labels[j//2]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_43_no_35-english.pdf at pdf_to_rtf(). Perhaps the file is not a proper PDF?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 121, in <module>
    rtfData = pdf_to_rtf(currentFile)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\Modules\pdf_extractor.py", line 41, in pdf_to_rtf
    text = page.extract_text()
  File "C:\Users\pasarm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\PyPDF2\_page.py", line 1851, in extract_text
    return self._extract_text(
  File "C:\Users\pasarm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\PyPDF2\_page.py", line 1342, in _extract_text
    cmaps[f] = build_char_map(f, space_width, obj)
  File "C:\Users\pasarm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\PyPDF2\_cmap.py", line 24, in build_char_map
    font_type: str = cast(str, ft["/Subtype"])
  File "C:\Users\pasarm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\PyPDF2\generic\_data_structures.py", line 266, in __getitem__
    return dict.__getitem__(self, key).get_object()
KeyError: '/Subtype'

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_44_no_13-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_45_no_02-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 262, in convert_to_table
    cases = table_values[i-2][j-1]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_45_no_03-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 260, in convert_to_table
    long, lat, region_type, country_code, region_boundary = get_location_info(location_name)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\../../Modules\location_interface.py", line 128, in get_location_info
    raise ValueError
ValueError

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_45_no_04-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 260, in convert_to_table
    long, lat, region_type, country_code, region_boundary = get_location_info(location_name)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\../../Modules\location_interface.py", line 128, in get_location_info
    raise ValueError
ValueError

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_45_no_45-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 263, in convert_to_table
    disease_name = labels[j//2]
IndexError: list index out of range

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_46_no_18-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 193, in convert_to_table
    rows = important_text[1].split('\n')
AttributeError: 'NoneType' object has no attribute 'split'

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_46_no_23-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 260, in convert_to_table
    long, lat, region_type, country_code, region_boundary = get_location_info(location_name)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\../../Modules\location_interface.py", line 128, in get_location_info
    raise ValueError
ValueError

Error for file Data/Sri Lanka Weekly Reports Post 2013/vol_49_no_07-english.pdf at model.extract_to_table(). Perhaps you chose the wrong model or have an error in the model?
Traceback (most recent call last):
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\dataParser.py", line 123, in <module>
    table,heading = model.extract_to_table(rtfData, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\sriLankaParser.py", line 43, in extract_to_table
    table = convert_to_table(important_text, timestamps, flags = flags)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\convert_to_table.py", line 260, in convert_to_table
    long, lat, region_type, country_code, region_boundary = get_location_info(location_name)
  File "C:\Users\pasarm\Documents\Github\disease_data_parser_MLOS2\ParsingModels\SriLankaModules\../../Modules\location_interface.py", line 128, in get_location_info
    raise ValueError
ValueError

There were errors in 87/554 files